### ISSUE TITLE
Ligatures for == not working, but -> are working?

### ISSUE THREAD

**Issue by pkazmier** [eigilnikolajsen/commit-mono#32] opened 2023-08-18 13:03 UTC
I customized my download to enable ligatures for the set of equal signs as well as for the arrows, but only arrows are actually working. I've tested this in multiple terminals (WezTerm, Kitty) and it's the same. I downloaded the version from the website this morning. Font book tells me it's version 1.134. 

<img width="464" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/747855/b0d44ad6-62f4-4d14-9ff5-1169061a4745">

I've even tried to manually enable them by setting the the stylistic sets explicitly thinking maybe they just were baked in, but that also did not work. I then tried to download the font without the equal ligatures from the website thinking maybe the toggle was reversed by accident—nope, didn't work.

I've used lots of fonts with ligatures in the past and know how to enable settings such as call and ssNN features, so I don't believe this is user error, but I've exhausted my knowledge of how to troubleshoot this further.

**Comment by shurizzle** [comment] 2023-08-31 22:15
<img width="265" alt="immagine" src="https://github.com/eigilnikolajsen/commit-mono/assets/203655/2653e616-f8fb-4841-9ea2-6785012586ed">

I this can be useful: this is neovim in wezterm. Looks like those symbol's ligatures works only in strings.

**Comment by eigilnikolajsen** [comment] 2023-09-01 05:55
Very useful, thank you. I'm actually inclined to believe that neovim doesn't use the space character. Let me explain.
The feature is built to only substitute symbols when surrounded by spaces. But the space isn't the only character, I've defined a group of 'space actors' which the quotes you show are part of. 
The part that surprises me is that space does not work, but these do. Thank you for your test, I will see what I can do.

**Comment by inudev5** [comment] 2023-09-20 17:07
it's not a vim issue. its reproduced in vscode also.

**Comment by shurizzle** [comment] 2023-11-07 11:02
![image](https://github.com/eigilnikolajsen/commit-mono/assets/203655/f4c8165a-1e9d-4440-a09c-d879f41547d7)
I guess this issue can be marked as solved, right

**Comment by eigilnikolajsen** [comment] 2023-11-07 11:17
Yes, it can, thank you!

**Closed by eigilnikolajsen** 2023-11-07 11:17 UTC
Labels: Bug
